import type { RescuerVerification } from "@/types/admin-pages";

export const mockRescuerVerifications: RescuerVerification[] = [
  {
    id: "1",
    rescuerId: "rescuer-001",
    rescuerName: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "0901234001",
    region: "Thừa Thiên Huế",
    status: "pending",
    documents: [
      {
        id: "doc1",
        type: "id",
        url: "/documents/verification/id-1.pdf",
        name: "CMND/CCCD",
        verified: false,
      },
      {
        id: "doc2",
        type: "certificate",
        url: "/documents/verification/cert-1.pdf",
        name: "Chứng chỉ cứu hộ",
        verified: false,
      },
      {
        id: "doc3",
        type: "background-check",
        url: "/documents/verification/bg-1.pdf",
        name: "Lý lịch tư pháp",
        verified: false,
      },
    ],
    profile: {
      experience: "5 năm kinh nghiệm cứu hộ, từng tham gia nhiều chiến dịch cứu hộ thiên tai",
      skills: ["Bơi lội", "Sơ cấp cứu", "Leo núi", "Lái thuyền"],
      certifications: ["Chứng chỉ cứu hộ cơ bản", "Chứng chỉ sơ cấp cứu"],
      previousWork: "Từng làm việc tại đội cứu hộ tỉnh Thừa Thiên Huế",
    },
    submittedAt: "2024-12-19T10:00:00Z",
    history: [
      {
        action: "submitted",
        timestamp: "2024-12-19T10:00:00Z",
      },
    ],
  },
  {
    id: "2",
    rescuerId: "rescuer-002",
    rescuerName: "Trần Thị B",
    email: "tranthib@example.com",
    phone: "0901234002",
    region: "Đà Nẵng",
    status: "pending",
    documents: [
      {
        id: "doc4",
        type: "id",
        url: "/documents/verification/id-2.pdf",
        name: "CMND/CCCD",
        verified: true,
        verifiedAt: "2024-12-20T08:00:00Z",
        verifiedBy: "admin@sosresq.vn",
      },
      {
        id: "doc5",
        type: "license",
        url: "/documents/verification/license-1.pdf",
        name: "Giấy phép lái thuyền",
        verified: true,
        verifiedAt: "2024-12-20T08:15:00Z",
        verifiedBy: "admin@sosresq.vn",
      },
      {
        id: "doc6",
        type: "certificate",
        url: "/documents/verification/cert-2.pdf",
        name: "Chứng chỉ cứu hộ",
        verified: false,
      },
    ],
    profile: {
      experience: "3 năm kinh nghiệm, chuyên về cứu hộ trên biển",
      skills: ["Bơi lội", "Lặn", "Sơ cấp cứu", "Lái thuyền"],
      certifications: ["Chứng chỉ cứu hộ biển", "Chứng chỉ lặn"],
    },
    submittedAt: "2024-12-18T14:30:00Z",
    history: [
      {
        action: "submitted",
        timestamp: "2024-12-18T14:30:00Z",
      },
      {
        action: "reviewed",
        timestamp: "2024-12-20T08:00:00Z",
        by: "admin@sosresq.vn",
        note: "Đã xác minh CMND và giấy phép lái thuyền",
      },
    ],
  },
  {
    id: "3",
    rescuerId: "rescuer-003",
    rescuerName: "Lê Văn C",
    email: "levanc@example.com",
    phone: "0901234003",
    region: "Quảng Nam",
    status: "verified",
    documents: [
      {
        id: "doc7",
        type: "id",
        url: "/documents/verification/id-3.pdf",
        name: "CMND/CCCD",
        verified: true,
        verifiedAt: "2024-12-15T09:00:00Z",
        verifiedBy: "admin@sosresq.vn",
      },
      {
        id: "doc8",
        type: "certificate",
        url: "/documents/verification/cert-3.pdf",
        name: "Chứng chỉ cứu hỏa",
        verified: true,
        verifiedAt: "2024-12-15T09:30:00Z",
        verifiedBy: "admin@sosresq.vn",
      },
      {
        id: "doc9",
        type: "background-check",
        url: "/documents/verification/bg-2.pdf",
        name: "Lý lịch tư pháp",
        verified: true,
        verifiedAt: "2024-12-15T10:00:00Z",
        verifiedBy: "admin@sosresq.vn",
      },
    ],
    profile: {
      experience: "7 năm kinh nghiệm, từng là lính cứu hỏa",
      skills: ["Cứu hỏa", "Sơ cấp cứu", "Sử dụng thiết bị cứu hộ", "Quản lý khủng hoảng"],
      certifications: ["Chứng chỉ cứu hỏa", "Chứng chỉ quản lý khủng hoảng"],
      previousWork: "Lính cứu hỏa tỉnh Quảng Nam (2017-2024)",
    },
    submittedAt: "2024-12-15T08:00:00Z",
    reviewedAt: "2024-12-15T10:30:00Z",
    reviewedBy: "admin@sosresq.vn",
    comments: "Đã xác minh đầy đủ. Phê duyệt thành công.",
    history: [
      {
        action: "submitted",
        timestamp: "2024-12-15T08:00:00Z",
      },
      {
        action: "reviewed",
        timestamp: "2024-12-15T09:00:00Z",
        by: "admin@sosresq.vn",
        note: "Bắt đầu xác minh tài liệu",
      },
      {
        action: "approved",
        timestamp: "2024-12-15T10:30:00Z",
        by: "admin@sosresq.vn",
        note: "Đã xác minh và phê duyệt",
      },
    ],
  },
];
