import type { RescueReport, ReportStats } from "@/types/admin-pages";

export const mockRescueReports: RescueReport[] = [
  {
    id: "1",
    title: "Cứu hộ gia đình bị mắc kẹt trong lũ",
    type: "rescue",
    status: "completed",
    location: "Phường Phú Hội, TP. Huế",
    region: "Thừa Thiên Huế",
    date: "2024-12-19T14:30:00Z",
    reporter: "citizen1@example.com",
    description: "Gia đình 4 người bị mắc kẹt trong nhà do nước lũ dâng cao. Đã được cứu hộ thành công.",
    casualties: 0,
    rescued: 4,
    fileUrl: "/reports/report-1.pdf",
  },
  {
    id: "2",
    title: "Sơ tán người dân khỏi vùng ngập lụt",
    type: "evacuation",
    status: "in-progress",
    location: "Huyện Nam Giang, Quảng Nam",
    region: "Quảng Nam",
    date: "2024-12-20T08:00:00Z",
    reporter: "coordinator1@sosresq.vn",
    description: "Đang tiến hành sơ tán 50 hộ dân khỏi vùng ngập lụt. Dự kiến hoàn thành trong 2 giờ.",
    rescued: 25,
    fileUrl: "/reports/report-2.pdf",
  },
  {
    id: "3",
    title: "Cung cấp lương thực cho vùng bị cô lập",
    type: "supply",
    status: "pending",
    location: "Huyện Đông Giang, Quảng Nam",
    region: "Quảng Nam",
    date: "2024-12-20T10:00:00Z",
    reporter: "coordinator2@sosresq.vn",
    description: "Cần cung cấp lương thực, nước uống và thuốc men cho 3 thôn bị cô lập do lũ lụt.",
  },
  {
    id: "4",
    title: "Cấp cứu người bị thương do sạt lở đất",
    type: "medical",
    status: "completed",
    location: "Huyện Tây Giang, Quảng Nam",
    region: "Quảng Nam",
    date: "2024-12-18T16:45:00Z",
    reporter: "rescuer1@sosresq.vn",
    description: "1 người bị thương do sạt lở đất. Đã được đưa đến bệnh viện và điều trị ổn định.",
    casualties: 1,
    rescued: 1,
    fileUrl: "/reports/report-4.pdf",
  },
  {
    id: "5",
    title: "Báo cáo thiệt hại sau lũ lụt",
    type: "other",
    status: "completed",
    location: "Quận Hải Châu, Đà Nẵng",
    region: "Đà Nẵng",
    date: "2024-12-17T11:20:00Z",
    reporter: "citizen2@example.com",
    description: "Báo cáo thiệt hại về nhà cửa và tài sản sau đợt lũ lụt vừa qua.",
    fileUrl: "/reports/report-5.pdf",
  },
];

export const mockReportStats: ReportStats = {
  total: 5,
  pending: 1,
  inProgress: 1,
  completed: 3,
  cancelled: 0,
};
