import type { WeatherPost } from "@/types/admin-pages";

export const mockWeatherPosts: WeatherPost[] = [
  {
    id: "1",
    title: "Cảnh báo mưa lớn khu vực Thừa Thiên Huế",
    content: "Dự báo mưa lớn từ ngày 21-23/12 với lượng mưa có thể lên đến 200-300mm. Người dân cần chú ý đề phòng lũ lụt và sạt lở đất.",
    imageUrl: "/images/weather-1.jpg",
    publishDate: "2024-12-20T08:00:00Z",
    status: "published",
    author: "admin@sosresq.vn",
    views: 1250,
    category: "alert",
  },
  {
    id: "2",
    title: "Thời tiết tuần này - Miền Trung",
    content: "Tuần này thời tiết ổn định, nhiệt độ dao động 22-28°C. Có mưa nhỏ rải rác vào chiều tối.",
    publishDate: "2024-12-19T07:00:00Z",
    status: "published",
    author: "coordinator1@sosresq.vn",
    views: 890,
    category: "weather",
  },
  {
    id: "3",
    title: "Cảnh báo lũ quét tại Quảng Nam",
    content: "Cảnh báo lũ quét có thể xảy ra tại các huyện miền núi Quảng Nam trong 24h tới. Người dân cần di chuyển đến nơi an toàn.",
    imageUrl: "/images/flood-alert.jpg",
    scheduledDate: "2024-12-21T06:00:00Z",
    status: "scheduled",
    author: "admin@sosresq.vn",
    views: 0,
    category: "flood",
  },
  {
    id: "4",
    title: "Dự báo thời tiết tháng 12",
    content: "Tháng 12 có nhiều đợt không khí lạnh, nhiệt độ giảm sâu. Cần chú ý giữ ấm và đề phòng các bệnh về đường hô hấp.",
    status: "draft",
    author: "coordinator1@sosresq.vn",
    views: 0,
    category: "weather",
  },
  {
    id: "5",
    title: "Tình hình lũ lụt tại Đà Nẵng",
    content: "Mực nước sông Hàn đang ở mức báo động 2. Các khu vực ven sông cần đề phòng ngập lụt.",
    imageUrl: "/images/flood-situation.jpg",
    publishDate: "2024-12-18T14:00:00Z",
    status: "published",
    author: "coordinator2@sosresq.vn",
    views: 2100,
    category: "flood",
  },
];
